Repository IN-SOPT-WEB-5/Client, pull requests merged in 2022-11, with the labels that each got.

#3 [ feat ]큰 Nav bar 의 Top mini nav bar 구현 완료
  src/@components/@common/GeneralNav.jsx
  src/@components/@common/Header.jsx
  src/@components/@common/LandingNav.jsx
  src/assets/header/ic_home.svg
  src/assets/header/ic_menu_black.svg
  src/assets/header/ic_my_black.svg
  src/assets/header/ic_search_black.svg
  src/assets/header/icn_cramp_gray.svg
  src/assets/header/navhamburger.svg
  src/assets/header/navlogo.svg
  src/assets/header/navmypage.svg
  src/assets/header/navsearchicon.svg
  src/assets/header/purplelogo.svg
  src/style/theme.js
Labels: feat, 현수

#11 Feat#4 UI
  package-lock.json
  src/@components/BookingPage/Calendar.jsx
  src/@components/BookingPage/MovieSelection.jsx
  src/@components/BookingPage/QuickReserve.jsx
  src/@components/BookingPage/SpecialType.jsx
  src/@components/BookingPage/TheaterSelection.jsx
  src/@components/BookingPage/TimeSelection.jsx
  src/@components/BookingPage/index.jsx
  src/Router.jsx
  src/assets/AfterDateArrow.svg
  src/assets/AgeLimit12.png
  src/assets/AgeLimit15.png
  src/assets/AgeLimit18.png
  src/assets/BeforeDateArrow.svg
  src/assets/BrunchTheater.svg
  src/assets/Calendar.svg
  src/assets/MorningTheater.svg
  src/assets/NightTheater.svg
  src/assets/OrderDropDown.svg
  src/assets/SpecialTheater.svg
  src/core/bookingPage.js
  src/style/theme.js
  yarn.lock
Labels: 혜은

#17 Feat#14 booking page
  src/@components/BookingPage/MovieSelection.jsx
  src/@components/BookingPage/QuickReserve.jsx
  src/@components/BookingPage/TheaterSelection.jsx
  src/@components/BookingPage/TimeSelection.jsx
  src/assets/TagDelete.svg
  src/core/bookingPage.js
  src/style/theme.js
Labels: feat, 혜은

#15 Feat#7 movie components
  src/@components/@common/Footer.jsx
  src/@components/@common/Header.jsx
  src/@components/@common/Router.jsx
  src/@components/boxoffice/Checkbox.jsx
  src/@components/boxoffice/Hover.jsx
  src/@components/boxoffice/Index.jsx
  src/@components/boxoffice/MovieCard.jsx
  src/@components/boxoffice/MovieCard1st.jsx
  src/@components/boxoffice/MovieSelect.jsx
  src/@components/boxoffice/Nav.jsx
  src/@components/boxoffice/TopBtn.jsx
  src/App.jsx
  src/Router.jsx
  src/assets/AddMovieBtn.png
  src/assets/Age.svg
  src/assets/CinemaBtn.svg
  src/assets/HeartBtn.svg
  src/assets/ImgPoster.png
  src/assets/Opacity.png
  src/assets/TicketingBtn.svg
  src/assets/TicketingBtnS.svg
  src/assets/ic_search_gray2.svg
  src/constants/hoverData.js
  src/constants/movieData.js
  src/style/theme.js
  yarn.lock
Labels: feat, 명지

#12 Feat#2 header#2
  src/@components/@common/GeneralNav.jsx
  src/@components/SeatSelectingPage/PersonnelSelecting.jsx
  src/@components/SeatSelectingPage/SeatSelecting.jsx
  src/@components/SeatSelectingPage/SeatSelectingPage.jsx
  src/Router.jsx
  src/assets/seatSelectingPage/PersonnelSelecting/SeatIcon/Disabled.svg
  src/assets/seatSelectingPage/PersonnelSelecting/SeatIcon/General.svg
  src/assets/seatSelectingPage/PersonnelSelecting/SeatIcon/Impossible.svg
  src/assets/seatSelectingPage/PersonnelSelecting/SeatIcon/Selected.svg
  src/assets/seatSelectingPage/PersonnelSelecting/SeatIcon/Sold.svg
  src/assets/seatSelectingPage/PersonnelSelecting/movieAge.svg
  src/assets/seatSelectingPage/PersonnelSelecting/moviePoster.png
Labels: 현수

#22 Feat#21 landing page benefits
  src/@components/@common/Header.jsx
  src/@components/LandingPage/Benefits.jsx
  src/Router.jsx
  src/assets/landingPage/benefits_main.png
  src/assets/landingPage/cardIcon.png
  src/assets/landingPage/giftIcon.png
  src/assets/landingPage/landing_img_event2.png
  src/assets/landingPage/landing_img_event3.png
  src/assets/landingPage/landing_img_event4.png
  src/assets/landingPage/membershipIcon.png
  src/assets/landingPage/storeIcon.png
Labels: feat, 지영

#23 Feat#13 seat page UI
  src/@components/SeatSelectingPage/PersonnelSelecting.jsx
  src/@components/SeatSelectingPage/SeatSelectingPage.jsx
  src/App.jsx
  src/Router.jsx
  src/assets/seatSelectingPage/PersonnelSelecting/BlackSeats.png
  src/assets/seatSelectingPage/PersonnelSelecting/Buttons/MinusButton.svg
  src/assets/seatSelectingPage/PersonnelSelecting/Buttons/PlusButton.svg
  src/assets/seatSelectingPage/PersonnelSelecting/SeatIcon/Impossible.svg
  src/assets/seatSelectingPage/PersonnelSelecting/SeatIcon/Sold.svg
  src/assets/seatSelectingPage/PersonnelSelecting/Seats.png
Labels: feat, 현수

#30 [ feat ] 예약정보 select 페이지로 넘겨주기
  src/@components/BookingPage/TimeSelection.jsx
  src/@components/BookingPage/index.jsx
  src/App.jsx
  src/Router.jsx
Labels: feat, 혜은

#34 Feat#26 movie title
  src/@components/SeatSelectingPage/PersonnelSelecting.jsx
  src/Router.jsx
Labels: feat, 현수

#39 Feat#36 get serever
  .gitignore
  src/@components/LandingPage/BoxOffice/MovieInfo.jsx
  src/@components/LandingPage/BoxOffice/index.jsx
  src/@components/LandingPage/Curation.jsx
  src/@components/LandingPage/Guide.jsx
  src/@components/SeatSelectingPage/PersonnelSelecting.jsx
  src/Router.jsx
  src/assets/landingPage/btn_call.png
  src/assets/landingPage/btn_help.png
  src/assets/landingPage/btn_lost.png
  src/assets/landingPage/btn_place.png
  src/assets/landingPage/btn_qa.png
  src/assets/landingPage/btn_rent.png
  src/assets/landingPage/guide_boutique.png
  src/assets/landingPage/guide_comfort.png
  src/assets/landingPage/guide_dolby.png
  src/assets/landingPage/guide_kids.png
  src/assets/landingPage/guide_mx.png
  src/assets/landingPage/guide_puppy.png
  src/core/api/api.js
Labels: feat, 지영

#38 [feat] 박스오피스 페이지 서버 데이터 연결
  src/@components/boxoffice/Hover.jsx
  src/@components/boxoffice/MovieCard.jsx
  src/@components/boxoffice/MovieCard1st.jsx
  src/@components/boxoffice/MovieSelect.jsx
  src/constants/severMovieData.jsx
Labels: feat, 명지

#41 [ refactor ] 전체 코드 리팩토링
  .eslintrc.json
  src/@components/@common/GeneralNav.jsx
  src/@components/@common/LandingNav.jsx
  src/@components/@common/Router.jsx
  src/@components/BookingPage/index.jsx
  src/@components/BoxofficePage/Checkbox.jsx
  src/@components/BoxofficePage/Hover.jsx
  src/@components/BoxofficePage/MovieCard.jsx
  src/@components/BoxofficePage/MovieCard1st.jsx
  src/@components/BoxofficePage/MovieSelect.jsx
  src/@components/BoxofficePage/Nav.jsx
  src/@components/BoxofficePage/TopBtn.jsx
  src/@components/BoxofficePage/index.jsx
  src/@components/LandingPage/BoxOffice/MovieInfo.jsx
  src/@components/LandingPage/BoxOffice/index.jsx
  src/@components/LandingPage/Curation.jsx
  src/@components/LandingPage/index.jsx
  src/@components/SeatSelectingPage/PersonnelSelecting.jsx
  src/@components/SeatSelectingPage/SeatSelecting.jsx
  src/@components/SeatSelectingPage/SeatSelectingPage.jsx
  src/@components/index.jsx
  src/Router.jsx
  src/constants/severMovieData.jsx
  src/core/api/api.js
  src/core/hoverData.js
  src/core/movieData.js
  src/style/globalStyle.js
Labels: feat, 지영
